# Based on https://github.com/serkodev/rabbitmq-cluster-docker
# This defines a rabbitmq cluster that stands behind a load balancer. It is mainly used to test
# the auto-discovery feature of the main Client Module.
services:
  rabbitmq1:
    image: rabbitmq:3.13-management
    hostname: rabbitmq1
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_ERLANG_COOKIE=12345678
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ../enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ../rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ../cert:/etc/rabbitmq/cert
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - rabbitmq

  rabbitmq2:
    image: rabbitmq:3.13-management
    hostname: rabbitmq2
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
      - RABBITMQ_ERLANG_COOKIE=12345678
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ../enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ../rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ../cert:/etc/rabbitmq/cert
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - rabbitmq

  rabbitmq3:
    image: rabbitmq:3.13-management
    hostname: rabbitmq3
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
      - RABBITMQ_ERLANG_COOKIE=12345678
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ../enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ../rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ../cert:/etc/rabbitmq/cert
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - rabbitmq

  haproxy:
    image: haproxy:2.7
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - 5551:5551
      - 5552:5552
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq

networks:
  rabbitmq:
