name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "lib/**"
      - "mix.exs"
      - "mix.lock"
      - "test/**"
      - ".github/workflows/ci.yaml"
  push:
    branches:
      - main
    paths:
      - "lib/**"
      - "mix.exs"
      - "mix.lock"
      - ".github/workflows/ci.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26"
          elixir-version: "1.15"
      
      - uses: actions/checkout@v3

      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./services/docker-compose.yaml"

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.unlock --all
          mix deps.get
          mix deps.compile

      - name: Compile app
        run: mix compile

      - name: Run tests
        run: mix test
